# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cross(object):
    def setupUi(self, Cross):
        Cross.setObjectName("Cross")
        Cross.resize(308, 352)
        Cross.setMinimumSize(QtCore.QSize(308, 352))
        self.centralwidget = QtWidgets.QWidget(Cross)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.cross_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.cross_pushButton.setObjectName("cross_pushButton")
        self.gridLayout.addWidget(self.cross_pushButton, 7, 0, 1, 5)
        self.v2_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.v2_lineEdit.setText("")
        self.v2_lineEdit.setObjectName("v2_lineEdit")
        self.gridLayout.addWidget(self.v2_lineEdit, 2, 4, 1, 1)
        self.u3_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.u3_lineEdit.setText("")
        self.u3_lineEdit.setObjectName("u3_lineEdit")
        self.gridLayout.addWidget(self.u3_lineEdit, 3, 2, 1, 1)
        self.v_label = QtWidgets.QLabel(self.centralwidget)
        self.v_label.setObjectName("v_label")
        self.gridLayout.addWidget(self.v_label, 1, 3, 1, 1)
        self.result_widget = QtWidgets.QWidget(self.centralwidget)
        self.result_widget.setObjectName("result_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.result_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addWidget(self.result_widget, 9, 0, 1, 6)
        self.u_label = QtWidgets.QLabel(self.centralwidget)
        self.u_label.setObjectName("u_label")
        self.gridLayout.addWidget(self.u_label, 1, 0, 1, 1)
        self.u1_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.u1_lineEdit.setText("")
        self.u1_lineEdit.setObjectName("u1_lineEdit")
        self.gridLayout.addWidget(self.u1_lineEdit, 1, 2, 1, 1)
        self.log_label = QtWidgets.QLabel(self.centralwidget)
        self.log_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.log_label.setObjectName("log_label")
        self.gridLayout.addWidget(self.log_label, 8, 0, 1, 6)
        self.v1_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.v1_lineEdit.setText("")
        self.v1_lineEdit.setObjectName("v1_lineEdit")
        self.gridLayout.addWidget(self.v1_lineEdit, 1, 4, 1, 1)
        self.v3_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.v3_lineEdit.setText("")
        self.v3_lineEdit.setObjectName("v3_lineEdit")
        self.gridLayout.addWidget(self.v3_lineEdit, 3, 4, 1, 1)
        self.u2_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.u2_lineEdit.setText("")
        self.u2_lineEdit.setObjectName("u2_lineEdit")
        self.gridLayout.addWidget(self.u2_lineEdit, 2, 2, 1, 1)
        self.u_widget = QtWidgets.QWidget(self.centralwidget)
        self.u_widget.setObjectName("u_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.u_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addWidget(self.u_widget, 0, 2, 1, 1)
        self.v_widget = QtWidgets.QWidget(self.centralwidget)
        self.v_widget.setObjectName("v_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.v_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addWidget(self.v_widget, 0, 4, 1, 1)
        Cross.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Cross)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 308, 22))
        self.menubar.setObjectName("menubar")
        Cross.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Cross)
        self.statusbar.setObjectName("statusbar")
        Cross.setStatusBar(self.statusbar)

        self.retranslateUi(Cross)
        QtCore.QMetaObject.connectSlotsByName(Cross)

    def retranslateUi(self, Cross):
        _translate = QtCore.QCoreApplication.translate
        Cross.setWindowTitle(_translate("Cross", "Cross Product Calculator"))
        self.cross_pushButton.setText(_translate("Cross", "Calculate u x v"))
        self.v_label.setText(_translate("Cross", "v:"))
        self.u_label.setText(_translate("Cross", "u:"))
        self.log_label.setText(_translate("Cross", "RESULT"))
